# Generated by Django 5.2.4 on 2026-05-06 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', 'Телефон должен быть в формате +7XXXXXXXXXX (10 цифр после +7)')]),
        ),
    ]
