# constants.py

# Пользователи
USER_FIRST_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 100

# Проекты
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

# Пагинация
PAGINATION_PAGE_SIZE = 12
